{
  "contest": 136,
  "handle": "cccz",
  "address": "0x74d754378a59Ab45d3E6CaC83f0b87E8E8719270",
  "risk": "3",
  "title": "InfinityStaker: The rescueETH function cannot rescue any ETH accidentally sent to the contract",
  "issueId": 23,
  "issueUrl": "https://github.com/code-423n4/2022-06-infinity-findings/issues/23"
}